[package]
name = "cm_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = { version = "1.0.1", default-features = false, features = ["atomic", "alloc"] }
clap = { version = "4.5.56", features = ["derive"] }
rmp-serde = "1.3.1"
serde = { version = "1.0.228", features = ["derive"] }

